const examplePapers = [
    {
        shortName: 'Transformer',
        title: 'Attention is All You Need',
        authors: 'Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Lukasz Kaiser, Illia Polosukhin',
        journal: 'NeurIPS',
        year: '2017',
        previewURL: 'https://arxiv.org/pdf/1706.03762.pdf',
        notes: ['All you need is all you need.'],
    },
    {
        shortName: 'GAN',
        title: 'Generative Adversarial Nets',
        authors: 'Ian J. Goodfellow, Jean Pouget-Abadie, Mehdi Mirza, Bing Xu, David Warde-Farley, Sherjil Ozair, Aaron Courville, Yoshua Bengio',
        journal: 'NeurIPS',
        year: '2014',
        previewURL: 'https://arxiv.org/pdf/1406.2661.pdf',
        notes: ['GAN is all you need.'],
    },
    {
        shortName: 'BERT',
        title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
        authors: 'Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova',
        journal: 'NAACL-HLT',
        year: '2019',
        previewURL: 'https://arxiv.org/pdf/1810.04805.pdf',
        notes: [''],
    },
    {
        shortName: 'YOLO',
        title: 'You Only Look Once: Unified, Real-Time Object Detection',
        authors: 'Joseph Redmon, Santosh Divvala, Ross Girshick, Ali Farhadi',
        journal: 'CVPR',
        year: '2016',
        previewURL: 'https://arxiv.org/pdf/1506.02640.pdf',
        notes: [''],
    },
    {
        shortName: 'ResNet',
        title: 'Deep Residual Learning for Image Recognition',
        authors: 'Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun',
        journal: 'CVPR',
        year: '2016',
        previewURL: 'https://arxiv.org/pdf/1512.03385.pdf',
        notes: [''],
    },
    {
        shortName: 'Word2Vec',
        title: 'Efficient Estimation of Word Representations in Vector Space',
        authors: 'Tomas Mikolov, Kai Chen, Greg Corrado, Jeffrey Dean',
        journal: 'ICLR',
        year: '2013',
        previewURL: 'https://arxiv.org/pdf/1301.3781.pdf',
        notes: [''],
    },
    {
        shortName: 'Pix2Pix',
        title: 'Image-to-Image Translation with Conditional Adversarial Networks',
        authors: 'Phillip Isola, Jun-Yan Zhu, Tinghui Zhou, Alexei A. Efros',
        journal: 'CVPR',
        year: '2017',
        previewURL: 'https://arxiv.org/pdf/1611.07004.pdf',
        notes: [''],
    },
    {
        shortName: 'WaveNet',
        title: 'WaveNet: A Generative Model for Raw Audio',
        authors: 'Aaron van den Oord, Sander Dieleman, Heiga Zen, Karen Simonyan, Oriol Vinyals, Alex Graves, Nal Kalchbrenner, Andrew Senior, Koray Kavukcuoglu',
        journal: 'arXiv',
        year: '2016',
        previewURL: 'https://arxiv.org/pdf/1609.03499.pdf',
        notes: [''],
    },
];

export default examplePapers;
